PR про DTO-шки и удаление аккаунта из бд
murloteg/Chipped-Pets-Helper pull request #11
Opened 2023-07-08 06:04 UTC by murloteg

- добавил DTO для сущностей User и Pet
- переписал сервисы, используя эти DTO-шки
- фича, позволяющая "удалять" аккаунт пользователя
- изменения в html-страничках

2023-07-08 08:17 UTC, Zertalian1 requested changes

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/PetController.java
> +    public String createPet(Pet pet, Principal principal){
передавать principal в сервис это ошибка, замени Principal principal на @AuthenticationPrincipal User principal

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/PetController.java
>      public String pets(Principal principal, Model model) {
передавать principal в сервис это ошибка, замени Principal principal на @AuthenticationPrincipal User principal

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/PetController.java
> +            model.addAttribute("pet", pet);
Это должно обеспечиваться средствами thymeleaf, в нём можно сделать проверку на null и отобразить кусок текста

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/UserController.java
> +    public String personalCabinet(Principal principal, Model model) {
так же, как с principal выше

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/UserController.java
> +    public String accountDeletionPage() {
Для операций delete использовать нужно не Get, а Delete

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/UserController.java
> +    @PostMapping("/user/delete")
DeleteMapping

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/UserController.java
> +    public String deleteAccount(Principal principal, Model model) {
Опять principal, поступать, как писал выше

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/dto/PetDto.java
> +    private final String sex;
Вроде, обсуждали, что пола будет 2

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/mappers/PetDtoMapper.java
> +                userDtoMapper.apply(pet.getUser())
а тут происходит ужас. У вас для животного человек загружается при обращении к полю, что вы успешно делаете при мапинге, но когда вы загружаете пользователя для него сразу выгружается список собак. возможно стоит написать код, который извлекал бы из бд нужную инфу

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/CustomUserDetailsService.java
> +        return userRepository.findByEmail(email).orElse(null);
ты уверен, что orElse(null) вообще сработает, там всё же исключение кидается

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    public List<PetDto> getPetsByPrincipal(Principal principal) {
не By Principal а ByUserId

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    public UserDto getUserByPrincipal(Principal principal) {
Это вообще лишнее будет, если с principal разобраться

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    private List<PetDto> getPets() {
это плохо, если у вас будет хотя бы 10к животных ваш сервис просто ляжет, сделайте пагинацию (постраничный вывод)

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +        Optional<User> possibleUser = userRepository.findByEmail(user.getEmail());
здесь явно случилось что-то страшное. Почему не удалять пользователя сразу, как у вас может появиться пользователь с подобным email, в чём смысл менять email?

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +    public UserDto getUserByPrincipal(Principal principal) {
Это уйдёт, если поправите principal

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/UserController.java
>          if (!userService.createUser(user)) {
Стоит сделать через исключение + контроллер-обработчик

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/dto/UserDto.java
> +    private final Set<Role> roles;
Зачем вам роль в дто

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/mappers/UserDtoMapper.java
> +    public User mapDtoToUser(UserDto userDto, User user) {
должен создаваться новый User, а не передаваться

2023-07-08 08:17 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    public void createPet(Principal principal, Pet pet) {
заменить principal на User

2023-07-08 10:49 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/UserController.java
> +    public String accountDeletionPage() {
Да, если бы у нас был rest api, то и delete, и put и update были бы доступны..
Но вот только мы юзаем html, в котором есть только get и post :(

2023-07-08 13:55 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +        Optional<User> possibleUser = userRepository.findByEmail(user.getEmail());
По ТЗ сотрудники спецслужб должны иметь привилегированный доступ к бд, чтобы отслеживать всех пользователей, то есть надо сохранять инфу и о тех юзерах, которые решили удалить свои аккаунты

2023-07-08 14:51 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/dto/UserDto.java
> +    private final Set<Role> roles;
Хотел сначала через dto-шку смотреть статус повышенных привилегий, но да, звучит глупо, когда можно просто запрос к бд сделать по id

2023-07-08 16:53 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    private List<PetDto> getPets() {
Почитаю об этом, но пока даже в теории не представляю, что как это реализовать

2023-07-09 13:16 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/mappers/PetDtoMapper.java
> +                userDtoMapper.apply(pet.getUser())
Пока совсем непонятно как это править
На текущий момент добавил еще одну dto-шку, содержащую те сведения о юзере, которые мы хотим возвращать при пробитии чипа

2023-07-09 14:14 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    private List<PetDto> getPets() {
Пока нет полноценной обработки страничек со стороны фронта, но бэк теперь их шлет

2023-07-09 14:49 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/UserController.java
> +    @PostMapping("/user/delete")
По причинам выше вряд ли это будет хорошо...

2023-07-09 15:44 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/UserController.java
> +    public String accountDeletionPage() {
Первый способ - использовать функционал Thymeleaf
https://stackoverflow.com/questions/24256051/delete-or-put-methods-in-thymeleaf
Второй способ - подключить библиотеку HTMX, которую вам, скорее всего, позже придётся использовать
https://htmx.org/docs/

Рекомендую использовать 1-й способ

2023-07-09 15:45 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/UserController.java
> +    @PostMapping("/user/delete")
по ответу выше, будет нормально)

2023-07-10 02:51 UTC, Zertalian1 requested changes

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/PetController.java
> +    public String petsList(@AuthenticationPrincipal User principal, Model model,
перенеси @AuthenticationPrincipal User principal, на новую строку

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/PetController.java
> +        if (principal.getRoles().contains(Role.ROLE_PRIVILEGED_ACCESS)) {
скобку на новую строку

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/PetController.java
> +                           @RequestParam(required = false, defaultValue = "0") int page,
используй Pageable для пагинации

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/UserController.java
>          if (!userService.createUser(user)) {
Исключение должен кидать сервис а не контроллер

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/exceptions/FailedUserCreationException.java
> +public class FailedUserCreationException extends RuntimeException {
Чем тебе обычные исключения не угодили
https://metanit.com/java/tutorial/4.3.php

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/enums/Sex.java
> +public enum Sex {
Чем тебе обычные enum не угодили
https://javarush.com/groups/posts/1963-kak-ispoljhzovatjh-klass-enum

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/dto/PetDto.java
> +    private final String sex;
пол всё ещё строкой

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/dto/UserInfoDto.java
> +    private final String alias;
Сокрытие данных и всё такое, но если я буду писать человеку, то я хотел бы обращаться к нему как минимум по имени

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/dto/UserRegistrationDto.java
> +    private final String alias;
Аналогично тексту в дто

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/CustomUserDetailsService.java
> +        Optional<User> user = userRepository.findByEmail(email);
Сделай через orElseThrow()
https://habr.com/ru/articles/346782/

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    public List<PetDto> petsList(PageRequest pageRequest) {
замени PageRequest на Pageable

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    public List<PetDto> petsListByUserId(User principal) {
если метод называется ByUserId, то в него должен передаваться id, а не весь user

2023-07-10 02:51 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/utils/UtilConsts.java
> +public final class UtilConsts {
Абсолютно ненужная штука, если сделать нормальные enum

2023-07-10 03:30 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/exceptions/FailedUserCreationException.java
> +public class FailedUserCreationException extends RuntimeException {
По поводу второго: не люблю работать c checked exception'ами, т.к. зачем пытаться восстанавливать состояние в блоке catch, если на стороне сервера произошла ошибка? Просто пробросить runtime exception и error controller его уже обработает

2023-07-10 05:13 UTC, Zertalian1 requested changes

2023-07-10 05:13 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/PetController.java
> +        if (principal.getRoles().contains(Role.ROLE_PRIVILEGED_ACCESS)) {
Отдельная страница для Гос служб, доступ обеспечивается средствами spring sequrity

2023-07-10 05:13 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/PetController.java
> +            Long userId = principal.getId();
внести получение id usera в вызов сервиса

2023-07-10 05:13 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/PetController.java
>          if (pet != null) {
Убрать, вынести логику проверки на null в html

2023-07-10 05:13 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/UserController.java
> +        model.addAttribute("user", principal);
переадресация на главную страницу

2023-07-10 07:46 UTC, Zertalian1 approved these changes

2023-07-10 07:46 UTC, merged