Переделал удаление юзера (теперь инфа пишется в отдельную таблицу), д…
murloteg/Chipped-Pets-Helper pull request #26
Opened 2023-07-13 05:44 UTC by murloteg

…обавил новые Entity для дальнейшнего расширения функционала приложения

2023-07-13 07:33 UTC, Zertalian1 requested changes

2023-07-13 07:33 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/entities/Property.java
> +    @ManyToMany(cascade = CascadeType.REFRESH, fetch = FetchType.LAZY, mappedBy = "properties")
связь между табличками не многое ко многим, а многие к одному

2023-07-13 07:33 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/entities/Feature.java
> +public class Feature {
Добавить ссылку на пользователя

2023-07-13 07:33 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/entities/Pet.java
> +    private boolean hasFeatures;
проверку на наличие особенностей можно сделать через длину списка особенностей

2023-07-13 15:34 UTC, Zertalian1 requested changes

2023-07-13 15:34 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +        return userRepository.findUserByUserId(userId)
Утащить в UserService

2023-07-13 15:34 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/mappers/PetInfoDtoMapper.java
> +        List<User> users = pet.getUsers();
бесполезная переменная, вызывай метод, передавая ему pet.getUsers()

2023-07-13 15:34 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
>      public void deletePet(String chipId) { // TODO: add this feature later
Очень интересно, назвать ветку delete-user-and-pets и оставить удаление с тудушкой

2023-07-13 15:37 UTC, Zertalian1 requested changes

2023-07-13 15:37 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/entities/Feature.java
> +    private User user;
Фичи должны удаляться вслед за юзером

2023-07-14 15:28 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
>      public void deletePet(String chipId) { // TODO: add this feature later
Обязательно реализуем!
Но попозже....

2023-07-15 04:57 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +        return userRepository.findUserByUserId(userId)
мы же обсуждали в пятницу, что стоит это переписать через анатацию @Query

2023-07-15 08:21 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +        return userRepository.findUserByUserId(userId)
Попытался использовать нативный запрос и пока что ловлю ошибку приведения типов (он не может кастануть Object в Pet) в методе findAllPetsByUserId [этот метод в UserRepository]. Поэтому пока закомментил ту часть кода

2023-07-17 08:17 UTC, Zertalian1 approved these changes

2023-07-17 08:24 UTC, merged