Добавил функционал, позволяющий указать особенности питомца при создании.
murloteg/Chipped-Pets-Helper pull request #34
Opened 2023-07-18 05:55 UTC by murloteg

Изменил html-ки (теперь на них отображаются добавленные особенности питомца)

2023-07-18 06:30 UTC, Zertalian1 requested changes

2023-07-18 06:30 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/dto/FeatureDto.java
> +    private LocalDateTime dateTime;
Если тебе не нужно указывать дату с точностью до минуты, секунды используй обычный LocalDate

2023-07-18 06:30 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/dto/PetCreationDto.java
> +    private final List<String> features;
Почему лист строк, а не лист FeatureDto

2023-07-18 06:30 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/entities/Feature.java
> +        this.dateTime = LocalDateTime.now();
опять же, если тебе нужна точность в день используй LocalDate
https://javarush.com/quests/lectures/questsyntaxpro.level16.lecture03

2023-07-18 06:30 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +        pet.setFeatures(createFeaturesFromPetCreationDto(principal, petCreationDto.getFeatures()));
почему это не в конструкторе

2023-07-18 06:30 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +    private List<Feature> createFeaturesFromPetCreationDto(User principal, List<String> featuresAsStrings) {
Здесь всё странно, начиная с того, что у тебя передаются особенности как строки, заканчивая их отдельным сохранением. У тебя в дтошке создания должен быть уже список фич, потом ты преобразуешь дто в животное, добавляешь его пользователю и сохраняешь

2023-07-18 06:30 UTC, Zertalian1 commented on find-my-pet/src/main/resources/.env
> -POSTGRES_DATABASE="DB-Find-my-pet"
а это куда делось

2023-07-18 07:07 UTC, murloteg commented on find-my-pet/src/main/resources/.env
> -POSTGRES_DATABASE="DB-Find-my-pet"
Так и задумывалось, мы у себя этот файлик в gitignorе добавили

2023-07-18 07:15 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +    private List<Feature> createFeaturesFromPetCreationDto(User principal, List<String> featuresAsStrings) {
Мы же решили, что у одного животного может быть несколько особенностей, а каждая особенность однозначно обладает определенным типом property.

То есть животное, у которого есть особенность кормления и необходимость в приеме лекарств, обладает списком особенностей, содержащем в себе два элемента:
1) "особенность кормления" - "описание кормления"
2) "лекарства" - "давать определенные препараты"

2023-07-18 07:28 UTC, Zertalian1 requested changes

2023-07-18 07:28 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +    private List<Feature> createFeaturesFromPetCreationDto(User principal, List<FeatureCreationDto> featureCreationDtoList) {
Почему ты не используешь мапер, в чём вообще смысл этой функции

2023-07-18 07:29 UTC, Zertalian1 commented on find-my-pet/src/main/resources/.env
> -POSTGRES_DATABASE="DB-Find-my-pet"
а как вы без этого файла будете на серваке поднимать?

2023-07-18 07:31 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +    private List<Feature> createFeaturesFromPetCreationDto(User principal, List<String> featuresAsStrings) {
Так у тебя же в фиче есть строка, кода всё это будет введено

2023-07-18 07:36 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +    private List<Feature> createFeaturesFromPetCreationDto(User principal, List<String> featuresAsStrings) {
почем вообще идёт итерация по Property.values().length, а не по списку особенностей

2023-07-18 07:36 UTC, murloteg commented on find-my-pet/src/main/resources/.env
> -POSTGRES_DATABASE="DB-Find-my-pet"
создадим такой же файлик под это дело, но уже на серваке
таким образом от комита к комиту не будет меняться его содрежимое

2023-07-18 07:50 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +    private List<Feature> createFeaturesFromPetCreationDto(User principal, List<String> featuresAsStrings) {
Почему ты итерируешься по enum? Зачем он вообще был создан? как ты можешь давать гарантии совпадения индексов, при добавлении значения в enum его придётся добавлять ещё и в таблицу?

Решения:
1) Убрать enum, итерироваться по списку, который ты получишь из PropertiesRepository и надеяться, что вы не будете забывать согласовывать бэк и фронт или добавить в дто поле, указывающее на то, какой это признак
2) Убрать класс и оставить только enum, конец предложения смотреть выше

2023-07-18 07:53 UTC, Zertalian1 commented on find-my-pet/src/main/resources/.env
> -POSTGRES_DATABASE="DB-Find-my-pet"
господь создал докер...

2023-07-18 09:18 UTC, Zertalian1 requested changes

2023-07-18 09:18 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +        return propertiesRepository.findById((long) ordinal).orElseThrow(
зачем делать запросы с поиском по id, если у тебя уже всё и так выгружено

2023-07-18 09:18 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +            featuresRepository.save(feature);
на сколько я помню, тебе самому не нужно вызывать save, оно должно и так сохранить при сохранении  юзера

2023-07-18 09:18 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/UserService.java
> +        List<Feature> features = new ArrayList<>();
можно заменить всё на 

List<PropertyType> propertyTypes = propertiesRepository.findAll();
        return IntStream.range(0, propertyTypes.size()).filter(i ->
                !featureCreationDtoList.get(i).getDescription().isEmpty()).mapToObj(i ->
                new Feature(
                        featureCreationDtoList.get(i).getDescription(),
                        propertyTypes.get(i),
                        principal
                )
        ).collect(Collectors.toList());

2023-07-19 03:42 UTC, Zertalian1 approved these changes

2023-07-19 03:42 UTC, merged