Добавил страницу с поиском питомца
murloteg/Chipped-Pets-Helper pull request #38
Opened 2023-07-20 07:40 UTC by osipover

2023-07-20 09:21 UTC, murloteg requested changes

2023-07-20 09:21 UTC, murloteg commented on find-my-pet/src/main/resources/html/pet-info.html
> +                                            <td class="data-table" th:text="${pet.breed}">Йорк</td>
Изменить "Йорк" на "тут будет порода животного"

2023-07-20 09:21 UTC, murloteg commented on find-my-pet/src/main/resources/html/pet-info.html
> +                                            <td class="data-table" th:text="${pet.sex}">Самец</td>
Как и выше

2023-07-20 09:21 UTC, murloteg commented on find-my-pet/src/main/resources/html/pet-info.html
> +                                            <td class="data-table" th:text="${pet.chipId}">123456789012345</td>
Как и выше

2023-07-20 09:21 UTC, murloteg commented on find-my-pet/src/main/resources/html/pet-info.html
> +                                            <td class="data-table" th:text="${pet.type}">Собака</td>
Как и ниже

2023-07-20 09:23 UTC, Zertalian1 submitted a review, later dismissed

2023-07-20 09:23 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/PetController.java
> +        model.addAttribute("chipId", chipId);
chipId есть в PetInfoDto

2023-07-21 08:59 UTC, murloteg requested changes

2023-07-21 08:59 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/ErrorController.java
> +
лишние пустые строчки

2023-07-21 08:59 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/controllers/PetController.java
> +        model.addAttribute("chipId", chipId);
добавил инфу в exception, но не убрал из контроллера

2023-07-21 09:05 UTC, murloteg approved these changes

2023-07-21 09:06 UTC, murloteg approved these changes

2023-07-21 09:08 UTC, merged