Изменение информации о пользователе и его питомцах
murloteg/Chipped-Pets-Helper pull request #39
Opened 2023-07-20 09:11 UTC by murloteg

2023-07-20 14:04 UTC, Zertalian1 requested changes

2023-07-20 14:04 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/dto/FeatureCreationDto.java
> +@Data
Сдэлай Getter

2023-07-20 14:04 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/utils/FeaturesConverter.java
> +    public List<Feature> convertFeaturesFromPetCreationDto(User principal, List<FeatureCreationDto> featureCreationDtoList) {
Переделать FeatureCreationDto так, чтобы там хранился id property, убрать зависимость от порядка хранимых и получаемых property

2023-07-20 14:04 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/mappers/PetEditDtoMapper.java
> +    public PetEditDto apply(Pet pet) {
убери репозиторий, лучше уж сделай обёртку над apply, принимающий список фич + это точно можно сделать через мапу, где первый проход по properties собаки, второй по списку существующих properties

2023-07-20 14:04 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    public void updatePetInfo(User principal, PetEditDto petEditDto) { // TODO: this method doesn't delete features from table
теоретически, если сделать в property и feature нормальную передачу id, то в идеале можно будет прям полученным списком заменять список фич, но стоит подумать, что будет если кто-то другой изменит фичи, пока мы на странице редактирования фич. план б - итерироваться по списку полученных фич, ища таковые в уже существующих у собаки

2023-07-20 14:04 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    public void updatePetInfo(User principal, PetEditDto petEditDto) { // TODO: this method doesn't delete features from table
для заполнения полей попробуй th:name='|pet.feature[${i.index}].property .id|'

2023-07-21 09:31 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    public void updatePetInfo(User principal, PetEditDto petEditDto) { // TODO: this method doesn't delete features from table
Пробовал и так и этак, но нифига не получается. Придется довольствоваться th:name="features", пока не станет понятно как это преодолеть :(

2023-07-21 10:38 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    public void updatePetInfo(User principal, PetEditDto petEditDto) { // TODO: this method doesn't delete features from table
а ты траил передавать пустой объект при сохдании?

2023-07-21 10:43 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    public void updatePetInfo(User principal, PetEditDto petEditDto) { // TODO: this method doesn't delete features from table
Да, так тоде пробовал. Страница отображалась корректно, но я ловил NPE уже в методе, обрабатывающем че там с веба пришло. Т.е. DTO-шка формировалась при таком подходе, но List<Feature> у нее был null

2023-07-21 11:07 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +    public void updatePetInfo(User principal, PetEditDto petEditDto) { // TODO: this method doesn't delete features from table
Есть поинт кстати сделать в PetCreationDto два списка:
1) список descriptions
2) список propertiesId

Тогда можно в hidden-поле id пробрасывать, но звучит как кринж

2023-07-24 10:32 UTC, Zertalian1 requested changes

2023-07-24 10:32 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/models/mappers/PetEditDtoMapper.java
> +        while (index < properties.size()) {
переделать на stream api

2023-07-24 10:32 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +                .orElseThrow(() -> new PetNotFoundException(message("api.server.error.pet-not-found")));
npe, перенести до map

2023-07-24 10:32 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +        List<Feature> oldFeatures = pet.getFeatures();
не нужно тянуть в отдельный лист

2023-07-24 10:32 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +                Feature value = featureMap.get(key);
сделать в один шаг, просто вызвать get(key)

2023-07-24 10:32 UTC, Zertalian1 commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +                Feature value = featureMap.get(key);
а лучше сделать через стрим

2023-07-25 02:54 UTC, murloteg commented on find-my-pet/src/main/java/ru/nsu/sberlab/services/PetService.java
> +                .orElseThrow(() -> new PetNotFoundException(message("api.server.error.pet-not-found")));
оказывается map - это метод класса Optional. так что тут все норм: если вернется пустой optional из findByChipId, то map ничего не сделает, и этот optional полетит в orElseThrow

2023-07-25 03:57 UTC, Zertalian1 approved these changes

2023-07-25 03:58 UTC, merged