Добавил функционал по загрузке и изменению фотографий питомцев
murloteg/Chipped-Pets-Helper pull request #55
Opened 2023-07-29 15:06 UTC by murloteg

- Фотки сохраняются на файловой системе, в бд лежит только название фотки (оно представляет из себя UUID + оригинальное название)

2023-07-29 15:09 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/repositories/PetImageRepository.java
> +public interface PetImageRepository extends JpaRepository<PetImage, Long> {
Потом может пригодится, но может и не пригодится)

2023-07-30 05:04 UTC, Zertalian1 requested changes

2023-07-30 05:04 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/FindMyPetApplication.java
> +@RequiredArgsConstructor
а зачем

2023-07-30 05:04 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/entities/PetImage.java
> +    @Column(name = "image_uuid_name")
если у тебя имя uuid, то возможно стоит использовать его как id

2023-07-30 05:04 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/exceptions/InternalServerErrorException.java
> +public class InternalServerErrorException extends RuntimeException {
а зачем? Назови как FileSysemException и добавь текс причины

2023-07-30 05:04 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/utils/PetImagesSaver.java
> +    private static final String FILE_SYSTEM_RESOURCES_PATH = "/src/main/resources/static/img/pet_images";
все эти константы вынеси в проперти

2023-07-30 05:04 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/utils/PetImagesSaver.java
> +public final class PetImagesSaver {
почему это не сервис?

2023-07-30 05:04 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/utils/PetImagesSaver.java
> +public final class PetImagesSaver {
можешь ещё сделать репозиторий, который будет отвечать за само сохранение

2023-07-30 05:04 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/repositories/PetImageRepository.java
> +public interface PetImageRepository extends JpaRepository<PetImage, Long> {
это что-то страшное и ненужное, если просто заменить id лонговый на id в виде названия файла

2023-07-30 07:35 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/models/entities/PetImage.java
> +    @Column(name = "image_uuid_name")
не,
uuid это такая штука: 7e5401ef-3a3d-4d0a-9de7-4f335ac0086d

2023-07-30 07:37 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/models/utils/PetImagesSaver.java
> +public final class PetImagesSaver {
Сохранение происходит при сохранении питомца. Так как питомец - владелец отношений

2023-07-30 07:37 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/repositories/PetImageRepository.java
> +public interface PetImageRepository extends JpaRepository<PetImage, Long> {
дропнул репозиторий, т.к. в нем нет смысла

2023-07-30 10:36 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/entities/PetImage.java
> +    @Column(name = "image_uuid_name")
да, эта штука уникальна и прочие слова про первичный ключ..

2023-07-30 10:58 UTC, Zertalian1 requested changes

2023-07-30 10:58 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/utils/PathResolver.java
> +public final class PathResolver {
создай репозиторий для картинок и перенеси это туда

2023-07-30 10:58 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/utils/ImageRemover.java
> +public final class ImageRemover {
создай репозиторий, вынеси это туда

2023-07-30 10:58 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/utils/PetCleaner.java
> +    private void removePetImage(PetImage petImage) {
это вынеси в репозиторий для картинок

2023-07-30 10:58 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/services/PetImageSaver.java
> +public class PetImageSaver {
есть ли тут бизнес логика - кажется нет, это штука, которая сохраняет файл - да -> это репозиторий

2023-07-30 11:52 UTC, murloteg commented on src/main/resources/html/edit-pet.html
> +                        <form th:method="put" th:action="@{/pet/edit}">
добавить enctype="multipart/form-data", иначе работать не будет

2023-07-30 12:31 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/models/entities/PetImage.java
> +    @Column(name = "image_uuid_name")
Пока оставим на Лонгах, ибо 
Resolved [org.springframework.orm.jpa.JpaSystemException: identifier of an instance of ru.nsu.sberlab.models.entities.PetImage was altered from 4d24af46-8371-4fc3-b262-9dc2ca4ca107 to 6d16cc8e-0135-4036-a7cc-dd3732e72080]
При замене UUID хочется и айдишник менять, но ему не нравится

2023-07-31 08:46 UTC, Zertalian1 requested changes

2023-07-31 08:46 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/repositories/PetImageRepositoryImpl.java
> +        if (imageFile.isEmpty()) {
Бизнес логика в репозитории мммм, по хорошему бы в сервис такое выносить, но учитывая, что мы торопимся, нужно сделать заметку, что нужно пофиксить в дальнейшем и сделать коментарий к методу об этом поведении

2023-07-31 08:46 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/repositories/PetImageRepositoryImpl.java
> +        if (imageFile.isEmpty()) {
аналогичная ситуация, подпиши, что при пустом файле метод просто делает retutn

2023-07-31 08:46 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/repositories/PetImageRepositoryImpl.java
> +        if (imageFile.isEmpty()) {
я бы ещё спросил, почему ты вызываешь удаление по 2 раза, но это завтра

2023-07-31 09:00 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/repositories/PetImageRepositoryImpl.java
> +        if (imageFile.isEmpty()) {
По поводу второго: зачем завтра, если можно сегодня!
Вопрос в целом ожидаемый и ответ такой: для того, чтобы приложение работало достаточно грузить фотки только в ../target/classes/static/img/pet_images. Это необходимый минимум, чтобы тянуть фотки на веб в рантайме. 
Но возникает один момент: если кто-то сделает "mvn clean", то вся директория target дропнется и, считай, вся база фоток питомцев тоже дропнется. Поэтому дополнительно надо сохранять фотки на фс, а не в папке target, у меня это: "static/img/pet_images". Тогда при пересборке приложения по пути target перетечет и наша база.
Эти фотки в гитигноре если что, так что они будут ток на фс сервака лежать.
Итак, в двух разных местах лежат фотки и нужно их как-то синхронизировать, поэтому я удаляю их из разных мест, ибо:
1) удаляю из static/img/pet_images, так как зачем хранить висячие фотки, которые не привязаны ни к какому питомцу
2) удаляю из target, так как, а если приложение перейдет в режим непрерывной работы, то зачем в этой директории тоже хранить большую кучу всего висячего

в итоге достигнута концепция, когда к одному животному и в бд и в фс привязана только одна фотка

2023-07-31 10:10 UTC, Zertalian1 approved these changes

2023-07-31 10:10 UTC, merged