Сохранение фотографий в базе данных + миграции для админов
murloteg/Chipped-Pets-Helper pull request #63
Opened 2023-09-03 11:43 UTC by murloteg

- Фотографии теперь сохраняются в базе данных, а не на файловой системе, как это было раньше
- Добавлены миграции для учетных записей администраторов (пока что две штуки)
- Небольшой рефакторинг кода

2023-09-03 13:05 UTC, Zertalian1 requested changes

2023-09-03 13:05 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/controllers/ImageController.java
> +        byte[] decodedImageData = Base64.getDecoder().decode(petImage.getImageData().getBytes());
вызов декодера это потенциальное место просадки производительности, зачем хранить изображение в виде строки(постоянно кодируя, декодируя), если его можно хранить в виде массива байт

2023-09-03 13:05 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/entities/PetImage.java
> +    private String imageData;
Можно хранить так
@Lob
@Column(name = "photo", columnDefinition="BLOB")
private byte[] photo;

https://www.baeldung.com/hibernate-lob

2023-09-03 13:05 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/mappers/PetEditDtoMapper.java
> +                new PetImageDto(pet.getPetImage().getImageUUIDName()),
если говорить честно, то в PetImageDto у тебя хранится не название изображения, а его uid, поэтому лучше переименовать, дав соответствующее название

2023-09-03 13:05 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/utils/DefaultImagesUtils.java
> +    @Value("${default.pet.image.name}")
тут назревает философский вопрос, нужна ли ошибка по изображениям и отдельная утила для дефолтных изображений, кажется, пользователь сам может прекрасно заметить, что вместо его собачки загрузилась какая-то кракозябра, поэтому можно убрать это, перенеся функционал отдачи дефолтных изображений.

2023-09-03 13:05 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/utils/PetCleaner.java
>  public class PetCleaner {
я в тг кидал ссылку на штуку, позволяющую делать автоматические удаления, тк я не вижу вашего таск борда, помечай такое хотя бы в коде

2023-09-03 13:05 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/services/PetService.java
>          try {
а к чему вообще ведёт этот try

2023-09-03 13:05 UTC, Zertalian1 commented on src/main/resources/db/migration/V1__create_db_tables.sql
> +    phone_number     varchar(255),
сомневаюсь, что у кого-то телефон или имя могут состоять из 255 символов, не есть конечно такие индивиды: Самое длинное имя в мире носит индиец по фамилии Брахматра. Оно состоит из 1478 букв. Но тогда либо просто стоит бахнуть текст, либо сожалеть об упущенном клиенте

2023-09-03 13:05 UTC, Zertalian1 commented on src/main/resources/db/migration/V1__create_db_tables.sql
> +    image_uuid_name varchar(255) unique,
в чём смысл иметь и uuid и id

2023-09-04 16:06 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/models/utils/DefaultImagesUtils.java
> +    @Value("${default.pet.image.name}")
Когда я это писал, то была идея сюда в перспективе накинуть и дефолтное изображение аватарки пользователя. если тот ничего не указал при регистрации (ну это в перспективе)

2023-09-05 09:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/models/utils/PetCleaner.java
>  public class PetCleaner {
Эта штука (orphalRemoval) используется у нас в User entity. Как я понял ее можно юзать только в OneToMany отношении со стороны One таким образом: если очистить коллекцию со стороны One, Hibernate сам удалит привязанные сущности, которые представляют сторону Many. По крайней мере, инфы про возможность такого использования в ManyToMany я не находил. А так у нас эта штука используется в UserService при удалении пользователя.

2023-09-05 15:44 UTC, Zertalian1 requested changes

2023-09-05 15:44 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/controllers/ImageController.java
> +        PetImage petImage = petImageRepository.findByImageUUIDName(uuidName).orElseThrow(ImageNotFoundException::new);
кидать исключение нужно в сервисе, а не в контроллере

2023-09-05 15:44 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/utils/DefaultImagesUtils.java
> +    @Value("${default.pet.image.name}")
ок, а зачем для этого какая-то утила

2023-09-05 15:44 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/utils/PetCleaner.java
>  public class PetCleaner {
ок, тогда смотри, у тебя же при удалении User в таблице users_pets удаляется запись, если так, то можно прописать удаление на стороне бд при помощи delete

2023-09-05 15:44 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/services/PetService.java
> +        PetImage petImage = pet.getPetImage();
здесь очень плохое происходит, зачем менять объект, если можно создать новый и переприсвоить +  зачем тягать нового узера по данным principal, если есть принципал

2023-09-05 15:44 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/services/UserService.java
> +                throw new CustomIOException(exception.getMessage());
CustomIOException очень странная ошибка, вообще непонятно, когда её использовать и для чего она нужна

2023-09-05 15:44 UTC, Zertalian1 commented on src/main/resources/db/migration/V4__create_admins.sql
> +INSERT INTO user_roles (user_id, roles) VALUES ('2', 'ROLE_ADMIN');
очень криво выглядит, почему не отношение многие ко многим. с ростом кол-ва клиентов, кол-во записей в таблице улетает в космос

2023-09-07 13:24 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/services/PetService.java
> +        PetImage petImage = pet.getPetImage();
По поводу principal: натыкались на ошибку, что сессия Hibernate не устанавливалась по нему, нужно из бд вытянуть конкретно юзера, тогда она устанавливается и все норм

2023-09-07 13:27 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/services/UserService.java
> +                throw new CustomIOException(exception.getMessage());
А это не знаю, как поправить. Хотел пробросить здесь RuntimeException, чтобы не париться над обработкой checked IOException (у нас так везде checked exception'ы обрабатываются). Пока не придумал хорошего названия для этого исключения

2023-09-07 13:39 UTC, murloteg commented on src/main/resources/db/migration/V4__create_admins.sql
> +INSERT INTO user_roles (user_id, roles) VALUES ('2', 'ROLE_ADMIN');
Вроде предполагалось, что один пользователь будет иметь только одну роль: зачем полицейскому аккаунту, например, роль обычного юзера, который может добавлять животных? Для этих целей можно создать обычный аккаунт, в соответствии с потребностью. Поэтому не вижу здесь смысла в отношении ManyToMany. Это первая причина. Вторая причина: мы используем аннотацию `@ElementCollection` (так как роль у нас не является entity => в данном случае не используются OneToMany и ManyToMany https://stackoverflow.com/questions/8969059/difference-between-onetomany-and-elementcollection)

2023-09-07 13:43 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/models/utils/PetCleaner.java
>  public class PetCleaner {
> ок, тогда смотри, у тебя же при удалении User в таблице users_pets удаляется запись, если так, то можно прописать удаление на стороне бд при помощи delete

Вот этот комментарий не понял совсем...
Но на всякий случай напомню, что животное может удалиться в двух случаях:
1) при удалении пользователя все его животные, фичи животных и тд и тп удаляется
2) при удалении животного фичи от животного открепляются, что позволяет юзеру иметь доступ к ранее созданным фичам (мб будет полезно позже), а само животное удаляется из бд.

так что в этих случаях утильная функция PetCleaner очень даже полезна

2023-09-07 13:46 UTC, murloteg commented on src/main/resources/db/migration/V1__create_db_tables.sql
> +    image_uuid_name varchar(255) unique,
Мне кажется, что будет неудобно сортировать фотки по UUID, все таки числа-индентификаторы воспринимаются мозгом проще, поэтому пусть останется числовой id, а uuidName будем считать названием фотки

2023-09-07 13:48 UTC, murloteg commented on src/main/resources/db/migration/V1__create_db_tables.sql
> +    phone_number     varchar(255),
Поле "first_name" поменял на тип text; поле "phone_number" оставил char(255)

2023-09-07 13:55 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/models/utils/DefaultImagesUtils.java
> +    @Value("${default.pet.image.name}")
Не знаю, как это по-другому можно реализовать, чтобы не добавлять в сервисы грубо говоря Bean'ы типа String, которые Spring заинжектит из application.properties. В итоге сделал утильный класс, в котором эти действия происходят, а после чего я уже в нужный сервис его подтягиваю и беру из него то, что нужно

2023-09-08 02:08 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/utils/DefaultImagesUtils.java
> +    @Value("${default.pet.image.name}")
а что с этим не так, пусть дефолтные изображения будут в сервисе и вообще их стоит засунуть в базу, а то у вас все изображения берутся из базы и только дефолтные лежат на файлухе

2023-09-08 02:24 UTC, Zertalian1 commented on src/main/resources/db/migration/V4__create_admins.sql
> +INSERT INTO user_roles (user_id, roles) VALUES ('2', 'ROLE_ADMIN');
ок, если пользователь имеет только одну роль, то зачем использовать смежную таблицу, в чём проблема хранить роль пользователя в таблице users, плюс нужно поменять тогда 
private Set<Role> roles = new HashSet<>();
на
private Role role;

2023-09-08 02:29 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/services/UserService.java
> +                throw new CustomIOException(exception.getMessage());
AddPetImageException

2023-09-16 02:13 UTC, Zertalian1 requested changes

2023-09-16 02:13 UTC, Zertalian1 commented on src/main/java/ru/nsu/sberlab/models/entities/User.java
> +        roles.add(role);
а почему не Set.of(role)

2023-09-17 05:28 UTC, Zertalian1 approved these changes

2023-09-17 05:28 UTC, merged