Реализовал капчу на главной странице
murloteg/Chipped-Pets-Helper pull request #69
Opened 2023-10-09 11:44 UTC by osipover

2023-10-09 12:56 UTC, murloteg requested changes

2023-10-09 12:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/services/ReCaptchaService.java
> +    private static final String VERIFY_URL = "https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s";
значений этой штуки лучше как property в application.properties и через аннотацию сюда подставлять

2023-10-09 12:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/services/ReCaptchaService.java
> +    public ReCaptchaService(ReCaptchaKeys reCaptchaKeys) {
я бы тут подумал над использованием аннотации RequiredArgsConstructor из lombock

2023-10-09 12:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/controllers/PetController.java
> +    @PostMapping("find")
а почему это Post запрос?
мы же выдаем инфу о питомце, а не создаем питомца

2023-10-09 12:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/recaptcha/ReCaptchaKeys.java
> +
лишний перенос строки

2023-10-09 12:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/recaptcha/ReCaptchaResponse.java
> +        return null;
если я правильно понял, то сейчас позитивный сценарий выглядит так:
ошибок нет -> возвращаем null.

если это действительно так, то это плохо
нужно использовать Collections.emptyList(), ибо рандомное NPE никто не отменял

2023-10-09 12:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/recaptcha/ReCaptchaResponse.java
> +        if (getErrorCodes() != null) {
используй Objects.[nonNull](https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#nonNull-java.lang.Object-)

2023-10-09 12:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/controllers/ErrorController.java
> +        return "redirect:" + exception.getRedirectURI();
возможно тут стоит добавить "/" после redirect:, а то потом будем путаться, что куда передавать.

а мб добавить чекер, который смотрит, есть ли знак '/' в начале переданного redirectURI и если нет, то автоматически добавляет после слова redirect:

2023-10-09 12:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/services/ReCaptchaService.java
> +    private final RestTemplate restTemplate = new RestTemplate();
а нужно ли это поле выносить отдельно?

кажется, т.к. этот template используется в одном месте, то можно его прямо в том методе и создавать.

если это было преградой перед ломбоковской аннотацией, то можно перенести инстанс

2023-10-09 12:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/services/ReCaptchaService.java
> +        if (reCaptchaResponse != null && (!reCaptchaResponse.isSuccess() ||
Objects.nonNull

2023-10-09 12:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/recaptcha/ReCaptchaResponse.java
> +    @JsonProperty("error-codes")
лучше поля с аннотациями ниже перенести, подальше от других, чтобы читалось попроще

2023-10-09 12:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/controllers/PetController.java
> +    private final ReCaptchaService reCaptchaSearchService;
я бы поменял reCaptchaSearchService просто на reCaptchaService

у нас же их логика в принципе одна и та же.
так что мне кажется это уточнение лишнее

2023-10-09 12:56 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/recaptcha/ReCaptchaErrorCodes.java
> +    public static final Map<String,String> RECAPTCHA_ERROR_CODES = Map.of(
пропущен пробел между типами: <String,String>

2023-10-09 16:46 UTC, osipover commented on src/main/java/ru/nsu/sberlab/controllers/ErrorController.java
> +        return "redirect:" + exception.getRedirectURI();
Не думаю, что это хорошая идея. Так как после redirect должен идти запрос, который он перенаправляет соответствующему контроллеру, и логично, что метод getRedirectURI должен возвращать сам запрос, который предполагает наличие "/" в начале. Можно тогда этот чекер, о котором ты говоришь, добавить внутрь метода getRedirectURI

2023-10-13 03:46 UTC, murloteg requested changes

2023-10-13 03:46 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/services/ReCaptchaService.java
> +        URI verifyURI = URI.create(String.format(this.verifyURI, reCaptchaKeys.getSecret(), response));
здесь поле verifyURI, объявленое локально, скроет поле класса ReCaptchaService.

можно либо переназвать переменную, чтобы не было сокрытия поля, либо изменять конкретно поле this.verifyURI

2023-10-13 03:46 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/exceptions/ReCaptchaException.java
> +    public List<String> getErrors() {
чтобы не писать стандартный getter, можно над конкретным полем (не классом) навесить аннотацию @Getter

2023-10-13 03:46 UTC, murloteg commented on src/main/java/ru/nsu/sberlab/recaptcha/ReCaptchaErrorCodes.java
> +public class ReCaptchaErrorCodes {
так как это утильный класс, то у него точно не должно быть инстансов.
чтобы защитится от них надо сделать его final (показываем, что он не участвует в иерархии наследования) и добавить private конструктор без аргументов, который бросает IllegalStateException.

2023-10-16 11:09 UTC, murloteg approved these changes

2023-10-16 11:09 UTC, merged